cart/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.cart_detail, name='cart'),
    path('success/', views.success, name='success')
]

interiorshop/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('vendors/', include('vendor.urls')),
    path('cart/', include('cart.urls')),
    path('', include('buyer.urls')),
    path('', include('core.urls')),
    path('products/', include('product.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/models.py
from django.db import models
# from product.
# # Create your models here.
# class CartPaid(models.Model):
#     product = 

core/models.py
import email
from django.db import models

# Create your models here.
class Contact(models.Model):
    name = models.CharField(max_length=255,null=False,blank=False)
    email = models.EmailField(null=False,blank=False)
    subject = models.CharField(max_length=255,null=False,blank=False)
    message = models.TextField(null=False,blank=False)
    def __str__(self):
        return self.email

# class Feedback(models.Model):
#     name=models.CharField(max_length=40)
#     feedback=models.CharField(max_length=500)
#     date= models.DateField(auto_now_add=True,null=True)
#     def __str__(self):
#         return self.name


class PopularClients(models.Model):
    client_name = models.CharField(max_length=255,null=False,blank=False)
    image = models.ImageField(upload_to = 'clients')
    ratting = models.PositiveIntegerField(blank=False,null=False,verbose_name='Client`s Ratting')

cart/forms.py
from django import forms


class CheckoutForm(forms.Form):
    first_name = forms.CharField(max_length=255)
    last_name = forms.CharField(max_length=255)
    email = forms.EmailField(max_length=255)
    phone = forms.CharField(max_length=255)
    address = forms.CharField(max_length=255)
    city = forms.CharField(max_length=255)
    # buyer = forms.(max_length=)

cart/views.py
from urllib import request
import stripe

from django.conf import settings
from django.contrib import messages
from django.shortcuts import render, redirect

from product.models import Category

from .cart import Cart
from .forms import CheckoutForm

from order.utilities import checkout, notify_customer, notify_ven


def cart_detail(request):
    if request.user.is_authenticated:
        cart = Cart(request)
        current_user = request.user.buyer
        categories = Category.objects.all()
        print(current_user)

        if request.method == 'POST':
            complete_name = request.POST.get('name', '')
            email = request.POST.get('email', '')
            phone = request.POST.get('phone', '')
            address = request.POST.get('address', '')
            city = request.POST.get('city', '')

            current_user.created_by.email = email
            current_user.created_by.save()

            current_user.complete_name = complete_name
            current_user.phone = phone
            current_user.address = address
            current_user.city = city
            current_user.save()
            order = checkout(request, cart.get_total_cost(), current_user)

            cart.clear()
            notify_customer(order)
            notify_ven(order)

            return redirect('success')
        else:
            form = CheckoutForm()
    else:
        return redirect('login')
    remove_from_cart = request.GET.get('remove_from_cart', '')
    change_quantity = request.GET.get('change_quantity', '')
    quantity = request.GET.get('quantity', 0)
    varient = request.GET.get('varient', '')

    if remove_from_cart:
        cart.remove(remove_from_cart)

        return redirect('cart')

    if change_quantity:
        cart.add(change_quantity, varient, quantity, True)

        return redirect('cart')

    return render(request, 'cart/cart.html', {'categories': categories})


def success(request):
    categories = Category.objects.all()

    return render(request, 'cart/success.html', {'categories': categories})

cart/templates/cart/cart.html
{% extends 'core/base.html' %} {% load static %} {% block content %}



<section class="meetings-page" style="color: white !important; padding: 20px !important; background: url(https://nel.com.pk/static/assets/images/meetings-page-bg.jpg) !important;">
  <h2 style="text-align: center;color:white;">Cart</h2>
  {% if cart %}
  <div class="container meetings-page header-text" id="meetings">
    <div class="row">
      <div class="col-lg-12">
        <div class="box-element">
          <a class="btn" href="{% url 'frontpage' %}" style="color: #dc3545; border-color: #dc3545;">&#x2190; Continue Shoping</a>
          <br /><br />
          <table class="table">
            <tr>
              <th>
                <h5 style="color: white;">Items: <strong>{{ cart|length}}</strong></h5>
              </th>
              <th>
                <h5 style="color: white;">Total: <strong>Rs.{{ cart.get_total_cost }}</strong></h5>
              </th>
              <th></th>
            </tr>
          </table>
        </div>
        <br />
        <div class="box-element">
          <div class="row">
            <div style="flex: 2"></div>
            <div style="flex: 1"><strong>Item</strong></div>
            <div style="flex: 1">Color</div>
            <div style="flex: 1"><strong>Price</strong></div>
            <div style="flex: 1"><strong>Quantity</strong></div>
            <div style="flex: 1"><strong>Total</strong></div>
            <div style="flex: 1"></div>
          </div>
          {% for item in cart %}
          <div class="row" style="justify-content: center; align-items: center;">
            <div style="flex: 2">
              <img style="width: 100px;" class="row-image" src="{{ item.product.get_thumbnail }}" />
            </div>
            <div style="flex: 1">{{ item.product.title }}</div>
            <div style="flex: 1">{{ item.product_varient }}</div>
            {% if item.product.discount_active == True%}
            <div style="flex: 1">Rs. {{ item.product.discounted_price }}</div>
            {% else %}
            <div style="flex: 1">Rs. {{ item.product.price }}</div>
            {% endif %}
            <div style="flex: 1; justify-content: center; align-items: center">
              <div style="display: flex;">
                <div class="quantity" style="align-self: center; margin-right: 10px;">{{ item.quantity }}</div>
                <div style="display: flex; flex-direction: column;">
                  <a href="?change_quantity={{ item.id }}&quantity=1" style="color: white;">&#11205;</a>
                  <a href="?change_quantity={{ item.id }}&quantity=-1" style="color: white;">&#9660;</a>
                </div>
              </div>
            </div>
            <div style="flex: 1">Rs.{{ item.total_price }}</div>
            <div style="flex: 1">
              <a class="btn btn-danger" href="?remove_from_cart={{ item.id }}" style="color: #dc3545; border-color: #dc3545;" class="delete"><i class="fa fa-trash"></i></a>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
  <br />
  <br />
  <div class="container meetings-page" id="meetings" style="padding-top: 20px !important;">
    <div class="row">
      <div class="col-lg-6">
        <div id="form-wraper" class="box-element">
          <form action="." method="post" id="payment-form" style="color: wh;">
            {% csrf_token %}
            <div class="mb-3">
              <label>Complete Name</label>
              <input type="text" name="name" id="id_name" value="{{ request.user.buyer.complete_name }}" class="form-control" />
            </div>
            <div class="mb-3">
              <label>E-mail</label>
              <input type="email" name="email" id="id_email" value="{{ request.user.buyer.created_by.email }}"
                class="form-control" />
            </div>
            <div class="mb-3">
              <label>Phone Number</label>
              <input type="text" name="phone" id="id_phone" value="{{ request.user.buyer.phone }}" class="form-control" />
            </div>
            <div class="mb-3">
              <label>Address</label>
              <input type="text" name="address" id="id_address" value="{{ request.user.buyer.address }}" class="form-control" />
            </div>
            <div class="mb-3">
              <label>City</label>
              <input type="text" name="city" id="id_city" value="{{ request.user.buyer.city }}" class="form-control" />
            </div>
            <button class="btn btn-success btn-block">Checkout</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  </div>
  <br><br>
  {% else %}
  <div class="container meetings-page" id="meetings" style="padding-top: 20px !important;">
    <p style="color: white; text-align: center;">You don't have any products in your cart!</p>
  </div>
  {% endif %}
  <div class="footer" style="background: transparent; color: white;">
    <p>Copyright © 2022 StarSOft.com.pk

  </div>
</section>
{% endblock %}

cart/templates/cart/success.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}



<section class="meetings-page" style="color: white;height:100vh;">
    <h1 style="text-align: center; color: white; text-transform: uppercase;" class="title">Thanks for the order</h1>
    <div class="footer" style="background: transparent;">
        <p>Copyright © 2022 StarSOft.com.pk

    </div>
</section>
{% endblock %}